apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc
  namespace: local-deploy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: wp-storage
  resources:
    requests:
      storage: 2Gi
